# Generated by Django 4.0.2 on 2022-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_alter_wallethistory_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=111)),
                ('api_string', models.CharField(max_length=199)),
            ],
        ),
    ]
