# Generated by Django 4.0.2 on 2022-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_apistrings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistrings',
            name='password',
            field=models.CharField(blank=True, default='', max_length=199),
        ),
    ]
