# Generated by Django 4.0.2 on 2022-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_userwallet_mail_userwallet_twitter_userwalletrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterHashTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_hash_tag', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='UserApiStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_api_name', models.CharField(max_length=111)),
                ('user_api_string', models.CharField(max_length=199)),
                ('user_api_password', models.CharField(blank=True, default='', max_length=199)),
            ],
        ),
    ]
