# Generated by Django 4.0.2 on 2022-04-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_twitterhashtags_user_userapistrings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletrequest',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.userapistrings'),
        ),
    ]
