# Generated by Django 4.0.2 on 2022-05-01 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0015_alter_userwalletrequest_minimum_income_to_spy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterhashtags',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.userwalletrequest'),
        ),
    ]
