# Generated by Django 4.0.2 on 2022-05-02 16:15

from django.db import migrations



def set_user_settings(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('auth', 'User')
    UserSettings = apps.get_model('coins', 'UserSettings')
    for user in User.objects.all():
        UserSettings.objects.create(user=user)



class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_usersettings'),
    ]

    operations = [
        migrations.RunPython(set_user_settings),
    ]
