# Generated by Django 4.0.2 on 2022-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_adress', models.CharField(max_length=42)),
                ('labels', models.CharField(max_length=100)),
            ],
        ),
    ]
