# Generated by Django 4.0.2 on 2022-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_adress', models.CharField(max_length=42)),
                ('label', models.CharField(max_length=100)),
                ('minimum_income_to_spy', models.CharField(max_length=10)),
                ('minimum_outcome_to_spy', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Wallets',
        ),
    ]
