# Generated by Django 4.0.2 on 2022-03-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_remove_wallet_minimum_income_to_spy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hash', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.wallet')),
            ],
        ),
    ]
