# Generated by Django 4.0.2 on 2022-03-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_apistrings_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='timestamp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.wallet'),
        ),
    ]
