# Generated by Django 4.0.2 on 2022-03-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_alter_wallethistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
