# Generated by Django 4.0.2 on 2022-04-16 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0009_alter_wallethistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserWalletRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_adress', models.CharField(max_length=42)),
                ('label', models.CharField(max_length=100)),
                ('minimum_income_to_spy', models.CharField(max_length=10)),
                ('minimum_outcome_to_spy', models.CharField(max_length=10)),
                ('twitter', models.BooleanField(default=False)),
                ('mail', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
