# Generated by Django 4.0.2 on 2022-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0013_userwalletrequest_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapistrings',
            name='user_api_string',
        ),
        migrations.AlterField(
            model_name='userwalletrequest',
            name='minimum_income_to_spy',
            field=models.CharField(default='0.1', max_length=10),
        ),
        migrations.AlterField(
            model_name='userwalletrequest',
            name='minimum_outcome_to_spy',
            field=models.CharField(default='0.1', max_length=10),
        ),
    ]
