# Generated by Django 4.0.2 on 2022-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_remove_userapistrings_user_api_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwalletrequest',
            name='minimum_income_to_spy',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=20, max_length=10),
        ),
        migrations.AlterField(
            model_name='userwalletrequest',
            name='minimum_outcome_to_spy',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=20, max_length=10),
        ),
    ]
