# Generated by Django 4.0.2 on 2022-05-04 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0018_auto_20220502_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterhashtags',
            name='mode',
            field=models.CharField(choices=[('h', 'HASH TAG'), ('u', 'ACCOUNT')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='twitterhashtags',
            name='twitter_username',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='twitterhashtags',
            name='twitter_hash_tag',
            field=models.CharField(blank=True, default='', max_length=42),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
